const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});
// Serve only the two deliverables: any runtime asset dependency must fail this test.
const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname.slice(1);if(!['index.html','ai-strategy-socratic-sandbox.aspx'].includes(name)){res.writeHead(404);return res.end()}res.setHeader('Content-Type','text/html');res.end(fs.readFileSync(path.join(root,name)))});
function fixture(kind){const S=require('../assets/workshop-state.js');const s=S.defaults();if(kind==='empty')return s;Object.assign(s.metadata,{agency:'Oregon Example Agency',title:'AI Adoption Strategy',version:'1.1',date:'2026-09-24'});for(let i=1;i<=10;i++){s.phases[i].context='PRIVATE_CONTEXT';s.phases[i].notes='PRIVATE_SCRATCHPAD';if(kind!=='partial'||i===1)s.phases[i].consensus='The agency will use AI to support public value while preserving human judgment and clear accountability.\nBusiness leadership will involve IT, privacy, security and data stewards before implementation.\n- Verify outputs against authoritative sources.\n- Escalate consequential decisions.\nThe accountable business owner will review progress and risks each quarter.'}if(kind==='edge'){s.metadata.agency='Very long agency & 公共 <special> : / \\ '.repeat(15)+'\u0000';s.metadata.version='v1/2';s.phases[1].consensus='Unicode café 公共 😀 & < > "\nLine break\n- Bullet A\n- Bullet B\n'+'Long consensus language that must wrap across pages safely. '.repeat(180)+'\u0000\ud800'}return s}
async function suite(channel,base){const browser=await chromium.launch({...(channel==='chromium'?{}:{channel}),headless:true});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write'],reducedMotion:'reduce'});const p=await context.newPage(),errors=[],unexpected=[],failed=[],scans=[];
 p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.method()!=='GET'||(!r.url().startsWith(base)&&!r.url().startsWith('blob:')))unexpected.push(r.url())});p.on('response',r=>{if(r.status()>=400)failed.push(r.url())});
 async function scan(name){if(!await p.evaluate(()=>!!window.axe))await p.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const v=await p.evaluate(async()=> (await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','best-practice']}})).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})));assert.deepEqual(v,[],name);scans.push(name)}
 async function noOverflow(){assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Horizontal overflow')}
 async function download(kind){const waiting=p.waitForEvent('download');await p.locator('#exportTopBtn').click();const d=await waiting;assert.ok(d.suggestedFilename().endsWith('.docx'));assert.ok(!/[<>:"/\\|?*]/.test(d.suggestedFilename()));await d.saveAs(path.join(out,channel+'-refresh-'+kind+'.docx'))}
 async function reset(){await p.locator('#resetBtn').click();await p.locator('[value=confirm]').click();await p.waitForFunction(()=>state[1].consensus===''&&JSON.parse(localStorage.getItem(STORAGE_KEY)).schemaVersion==='1.1')}
 await p.goto(base+'/index.html');assert.equal(await p.locator('#phaseTitle').innerText(),'Executive Summary');assert.equal(await p.locator('#setupPanel,#approveSection,#synthesisPanel').count(),0);assert.ok(!await p.locator('.report-details').getAttribute('open'));await scan('initial');await noOverflow();
 await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.className),'skip-link');await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>document.activeElement.id),'main');
 await p.locator('#tab-1').focus();for(const [key,id] of [['ArrowRight','tab-2'],['End','tab-10'],['ArrowRight','tab-1'],['ArrowLeft','tab-10'],['Home','tab-1']]){await p.keyboard.press(key);assert.equal(await p.evaluate(()=>document.activeElement.id),id);assert.equal(await p.locator('#'+id).getAttribute('aria-selected'),'true')}assert.equal(await p.locator('[role=tab][tabindex="0"]').count(),1);
 await p.locator('#contextInput').fill('PRIVATE_CONTEXT');await p.locator('#notesInput').fill('PRIVATE_AI');await p.locator('#starterChips button').first().click();assert.ok((await p.locator('#consensusInput').inputValue()).startsWith('Public value:'));assert.equal(await p.evaluate(()=>document.activeElement.id),'consensusInput');assert.equal(await p.locator('#phasePill').innerText(),'Captured');
 await p.locator('#consensusInput').fill('Human decision & <safe>\n- A safeguard');assert.ok((await p.locator('#draftScroll').innerText()).includes('Human decision'));assert.equal(await p.locator('#draftScroll li').count(),1);assert.ok(!(await p.locator('#draftScroll').innerText()).includes('PRIVATE_'));
 await p.locator('#copyPromptBtn').click();await p.waitForFunction(()=>document.querySelector('#toast').textContent.includes('Copied'));assert.ok((await p.evaluate(()=>navigator.clipboard.readText())).includes('PRIVATE_CONTEXT'));
 await p.locator('#copyDraftBtn').click();await p.waitForFunction(()=>document.querySelector('#toast').textContent.includes('Copied formatted'));assert.ok(!(await p.evaluate(()=>navigator.clipboard.readText())).includes('PRIVATE_'));
 await p.locator('#timerBtn').click();await p.waitForFunction(()=>timerSeconds<480);await p.locator('#timerBtn').click();const paused=await p.evaluate(()=>timerSeconds);await p.waitForTimeout(1100);assert.equal(await p.evaluate(()=>timerSeconds),paused);await p.evaluate(()=>{timerSeconds=1;updateTimerReadout()});await p.locator('#timerBtn').click();await p.waitForFunction(()=>timerSeconds===0&&timerHandle===null);await p.locator('#timerBtn').click();assert.ok(await p.evaluate(()=>timerSeconds>0));await p.locator('#timerBtn').click();
 await p.locator('#focusBtn').click();assert.ok(await p.locator('.draft').isHidden());await p.locator('#focusBtn').click();assert.equal(await p.locator('#focusBtn').getAttribute('aria-pressed'),'false');
 await p.locator('.report-details summary').click();await p.locator('#report-agency').fill('Agency report identity');await p.locator('#report-version').fill('1.2');await scan('report details');await p.reload();assert.equal(await p.locator('#consensusInput').inputValue(),'Human decision & <safe>\n- A safeguard');assert.equal(await p.locator('#report-agency').inputValue(),'Agency report identity');
 for(let i=1;i<=10;i++){await p.locator('#tab-'+i).click();assert.equal(await p.locator('#mediaGrid .media').count(),3);assert.equal(await p.locator('#starterChips button').count(),3);await p.locator('#contextInput').fill('Agency context '+i);assert.ok((await p.locator('#promptText').innerText()).includes('Agency context '+i));await p.locator('#starterChips button').last().click();assert.ok((await p.locator('#consensusInput').inputValue()).length>0);await p.locator('#consensusInput').fill('Section '+i+' consensus <img src="https://invalid.example/never" onerror="alert(1)">')}
 assert.ok((await p.locator('#progressText').innerText()).includes('10 of 10'));await p.locator('#nextBtn').click();assert.equal(await p.locator('#phaseTitle').innerText(),'Executive Summary');await p.locator('#prevBtn').click();assert.equal(await p.locator('#phaseTitle').innerText(),'Success Metrics and Evaluation');
 for(const width of [768,320]){await p.setViewportSize({width,height:900});await noOverflow();await scan('workshop '+width)}await p.screenshot({path:path.join(out,channel+'-refresh-mobile.png'),fullPage:true});
 await p.setViewportSize({width:1440,height:1000});await p.locator('#resetBtn').click();await scan('reset dialog');await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.activeElement.id),'resetBtn');
 await p.evaluate(()=>{localStorage.setItem('ai-strategy-socratic-sandbox-v1:'+location.pathname,JSON.stringify({1:{context:'V1 context',notes:'V1 scratchpad',consensus:'Original V1 decision'}}));localStorage.setItem('ai-strategy-socratic-sandbox-v2:'+location.pathname,'V2_PRESERVED');localStorage.removeItem(STORAGE_KEY)});await p.reload();assert.equal(await p.locator('#consensusInput').inputValue(),'Original V1 decision');assert.equal(await p.locator('#notesInput').inputValue(),'V1 scratchpad');await reset();await p.reload();assert.equal(await p.locator('#consensusInput').inputValue(),'');assert.ok((await p.evaluate(()=>localStorage.getItem('ai-strategy-socratic-sandbox-v1:'+location.pathname))).includes('Original V1 decision'));assert.equal(await p.evaluate(()=>localStorage.getItem('ai-strategy-socratic-sandbox-v2:'+location.pathname)),'V2_PRESERVED');
 await p.evaluate(()=>localStorage.setItem(STORAGE_KEY,'{broken'));await p.reload();assert.ok((await p.locator('#saveStatus').innerText()).includes('could not be loaded'));await p.locator('#consensusInput').fill('Unsaved decision');assert.equal(await p.evaluate(()=>localStorage.getItem(STORAGE_KEY)),'{broken');await reset();
 await p.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{value:undefined,configurable:true});document.execCommand=()=>true});await p.locator('#copyPromptBtn').click();assert.equal(await p.evaluate(()=>document.activeElement.id),'copyPromptBtn');await p.evaluate(()=>document.execCommand=()=>false);await p.locator('#copyPromptBtn').click();assert.ok((await p.locator('#toast').innerText()).includes('Copy blocked'));await p.reload();
 for(const kind of ['empty','partial','complete','edge']){await p.evaluate(value=>{var loadedFixture=WorkshopState.normalize(value);state=loadedFixture.phases;reportMetadata=loadedFixture.metadata;render();renderReportDetails()},fixture(kind));await download(kind)}
 await p.evaluate(value=>{state=value.phases;reportMetadata=value.metadata;current=1;render();renderReportDetails();scrollTo(0,0)},fixture('partial'));await p.screenshot({path:path.join(out,channel+'-refresh-desktop.png'),fullPage:true});
 await p.goto(base+'/ai-strategy-socratic-sandbox.aspx');assert.equal(await p.locator('#phaseTitle').innerText(),'Executive Summary');await download('aspx-empty');
 const isolated=path.join(out,'standalone',channel);fs.mkdirSync(isolated,{recursive:true});fs.copyFileSync(path.join(root,'index.html'),path.join(isolated,'index.html'));assert.deepEqual(fs.readdirSync(isolated),['index.html']);
 const offline=await browser.newContext({offline:true}),filePage=await offline.newPage(),fileErrors=[],fileRequests=[];filePage.on('pageerror',e=>fileErrors.push(e.message));filePage.on('request',r=>{if(!r.url().startsWith('file:')&&!r.url().startsWith('data:')&&!r.url().startsWith('blob:'))fileRequests.push(r.url())});await filePage.goto('file:///'+path.join(isolated,'index.html').replace(/\\/g,'/'));await filePage.locator('#contextInput').fill('Offline context');await filePage.locator('#starterChips button').first().click();await filePage.locator('#consensusInput').fill('Offline human decision');await filePage.reload();assert.equal(await filePage.locator('#consensusInput').inputValue(),'Offline human decision');const waitOffline=filePage.waitForEvent('download');await filePage.locator('#exportTopBtn').click();await (await waitOffline).saveAs(path.join(out,channel+'-refresh-offline.docx'));assert.deepEqual(fileErrors,[]);assert.deepEqual(fileRequests,[]);await offline.close();
 const denied=await context.newPage();await denied.addInitScript(()=>{Storage.prototype.getItem=function(){throw Error('denied')}});await denied.goto(base+'/index.html');assert.ok((await denied.locator('#saveStatus').innerText()).includes('could not be loaded'));await denied.locator('#consensusInput').fill('Session decision');assert.ok((await denied.locator('#draftScroll').innerText()).includes('Session decision'));await denied.close();
 const quota=await context.newPage();await quota.addInitScript(()=>{Storage.prototype.setItem=function(){throw Error('quota')}});await quota.goto(base+'/index.html');await quota.locator('#consensusInput').fill('Unsaved decision');assert.ok((await quota.locator('#saveStatus').innerText()).includes('Autosave unavailable'));await quota.close();
 assert.deepEqual(errors,[]);assert.deepEqual(unexpected,[]);assert.deepEqual(failed,[]);console.log(channel+': V1 interactions, 10 guide/chip/prompt exercises, storage migration/reset, clipboard, timer, '+scans.length+' axe scans and isolated offline HTML/DOCX passed.');fs.writeFileSync(path.join(out,channel+'-refresh-results.json'),JSON.stringify({channel,scans,errors,unexpected,failed,offline:'passed'},null,2));
}finally{await browser.close()}}
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;try{for(const channel of (process.env.BROWSER_CHANNELS||'chromium').split(','))await suite(channel,base)}finally{server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
